### ISSUE TITLE
Multiple instances not working... 

### ISSUE THREAD

**Issue by Snille** [diego-vieira/MMM-RandomPhoto#1]
Hi, I'm was thinking of using your nice module to display a personal wallpaper for each user on the mirror (using face recognition). But it seems that if there are more the one instance in the config of your module it is always the last instance picture that is shown. 
I'm using "classes" to show and hide your module.

Is this the case or have I done something wrong? :)

Best regards Erik

**Comment by diego-vieira** [comment]
@Snille tbh I didn't tested with multiple configurations.
Unfortunately I don't have much time to look into this ATM, however PRs are welcomed :)
